name: hexcore
description: A Flutter package which provides an interface to the League of Legends Client API (LCU API) and LCU Socket connection.
version: 1.0.1

repository: https://github.com/Lucasmaia435/hexcore

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
    
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

flutter:
  assets:
    - assets/certificate/riotgames.pem

platforms:
  windows: